title:            kosl90's Blog
description:      "Be gentle, be patient, be a man."
disqus_shortname:  kosl90
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:         http://kosl90.github.io
destination: kosl90.github.io

# Owner/author information
owner:
  name:           Lee
  avatar:         avatar.jpg
  bio:            "Be gentle, be patient, be a man."
  email:          kos1990l@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        kosl90
  facebook:       kosl90
  github:         kosl90
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   

# Background image to be tiled on all pages
background: retina_dust.png

# Analytics and webmaster tools stuff goes here
google_analytics:   
  id: 'UA-48343245-1'
  site: 'kosl90.github.io'
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
    - title: Feed
      url: /feed.xml
    - title: Old Blog
      url: http://blog.csdn.net/kosl90
      external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
pygments:    true
markdown:    redcarpet

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

# Amount of post to show on home page
paginate: 5

include: [".htaccess", ".nojekyll"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
